fail = open("viga.txt", encoding="UTF-8")
lause = fail.read()
lause = lause.replace(" et " , " , et ")
print(lause)
fail.close()
fail2 = open("par.txt", "w", encoding= "UTF-8")
fail2.write(lause)
fail2.close()